Vagrant.configure(2) do |config|
  config.vm.define "webserver" do |web|
    web.vm.box = "sbeliakou/centos-7.4-x86_64-minimal"
    web.vm.hostname = "webserver"
    web.vm.network :private_network, ip: "192.168.56.101"
    web.ssh.insert_key = false
    web.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "webserver"]
    end
    web.vm.provision "shell", path: "nginx.sh"
    web.vm.provision 'shell', inline: <<-EOF
    cp /vagrant/nginx.service /usr/lib/systemd/system/
    cp -f /vagrant/nginx.conf /home/vagrant/nginx/conf/
    sudo systemctl daemon-reload
    sudo systemctl start nginx
    sudo systemctl enable nginx
    EOF
  end

 (1..2).each do |i|
  config.vm.define "appserver#{i}" do |app|
    app.vm.box = "sbeliakou/centos-7.4-x86_64-minimal"
    app.vm.hostname = "appserver#{i}"
    app.vm.network :private_network, ip: "192.168.56.#{i + 101}"
    app.ssh.insert_key = false
    app.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 2048]
      v.customize ["modifyvm", :id, "--name", "appserver#{i}"]
    end
    app.vm.provision "shell", path: "app.sh"
  end
 end
end
